#spring.datasource.url: "jdbc:mysql://localhost:3306/waste_management"
#spring.datasource.username: root
#spring.datasource.password: ravi2108
persistence:
  user: root
  password: ravi2108
  databaseName: waste_management
  serverName: 127.0.0.1
  portNumber: 3306
  maximumPoolSize: 10
  connectionTimeout: 50000
  jdbcUrl: "jdbc:mysql://127.0.0.1:3306/waste_management"

inputFileBasePath: "F:\\Studies\\waste_management_server\\inputFile"


#spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.hibernate.ddl-auto : update
#logging.level.org.hibernate.SQL : DEBUG
#logging.level.org.hibernate.type : TRACE
  # Hibernate

  # The SQL dialect makes Hibernate generate better SQL for the chosen database


  # Hibernate ddl auto (create, create-drop, validate, update)
spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create

